### ISSUE TITLE
RuntimeError: tf.gradients is not supported when eager execution is enabled. Use tf.GradientTape instead.

### ISSUE THREAD

**Issue by HohyunH** [HaebinShin/grad-cam-text#2]

**Comment by hohohohyun** [comment]
> How to fix it?...
> 
> '''
> with tf.GradientTape() as tape:
> grads = tape.gradient(model.output[:,0], layers_wt)[0]
> '''
> 
> I tried this but it doesn't work,,,

**Comment by HaebinShin** [comment]
It seems like an error caused by TF2. This repo doesn't support TF2 yet, so using version 1.x would be fine.
